In [1]:
import tensorflow as tf
import numpy as np

/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/dtypes.py:519: FutureWarning: Passing (type, 1) or 

In [3]:
a = tf.constant(np.random.rand(3, 2, 2, 5), dtype=tf.float32)
x = a

In [6]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [8]:
sess.run(x)

array([[[[0.21668193, 0.05288194, 0.94911677, 0.62078345, 0.59650975],
         [0.610115  , 0.3216673 , 0.37463936, 0.09343854, 0.16760853]],

        [[0.200176  , 0.05431966, 0.13389105, 0.92559135, 0.71663034],
         [0.1216267 , 0.86508805, 0.8859746 , 0.89444184, 0.04948702]]],


       [[[0.57157767, 0.32710466, 0.06847334, 0.9089573 , 0.86125726],
         [0.43229046, 0.56822634, 0.3672753 , 0.06501245, 0.26721212]],

        [[0.7549424 , 0.69279325, 0.00627291, 0.74134314, 0.4837768 ],
         [0.10510538, 0.78369117, 0.03127609, 0.9086586 , 0.33178547]]],


       [[[0.8699226 , 0.04992506, 0.4703832 , 0.5484367 , 0.6916662 ],
         [0.8986387 , 0.79851395, 0.3341791 , 0.67818516, 0.7345151 ]],

        [[0.70913076, 0.755777  , 0.04884446, 0.1827714 , 0.37749782],
         [0.07498696, 0.5757642 , 0.7027297 , 0.78859097, 0.7415668 ]]]],
      dtype=float32)

In [9]:
#c = tf.reshape(x, [12, 20])

In [10]:
#sess.run(c)

In [11]:
#d = tf.pad(c, [[0, 1], [0, 1]])

In [12]:
#sess.run(d)

In [13]:
k = np.array([[1, 1], [1, 1]], dtype=np.float32)
inH = x.shape[1]
inW = x.shape[2]
minorDim = x.shape[3]
padx0=0
pady0=0
padx1=0
pady1=0
upx = 2
upy = 2
kernelH, kernelW = k.shape
x = tf.reshape(x, [-1, inH, 1, inW, 1, minorDim])
#x = tf.pad(x, [[0, 0], [0, 0], [0, upy - 1], [0, 0], [0, upx - 1], [0, 0]])
x = tf.pad(x, [[0, 0], [0, 0], [0, upy - 1], [0, 0], [0, upx - 1], [0, 0]])
x = tf.reshape(x, [-1, inH * upy, inW * upx, minorDim])

# Convolve with filter.
x = tf.transpose(x, [0, 3, 1, 2])
x = tf.reshape(x, [-1, 1, inH * upy + pady0 + pady1, inW * upx + padx0 + padx1])
w = tf.constant(k[:, :, np.newaxis, np.newaxis], dtype=x.dtype)
x = tf.pad(x, [[0, 0], [0, 0], [1, 0], [1, 0]])
y = tf.nn.conv2d(x, w, padding='VALID', data_format='NCHW', strides=1)
#y = tf.nn.conv2d(tf.transpose(x, [0, 2, 3, 1]), w, padding='SAME')
z = tf.transpose(x, [0, 2, 3, 1])
#x = tf.reshape(x, [-1, minorDim, inH * upy + pady0 + pady1 - kernelH + 1, inW * upx + padx0 + padx1 - kernelW + 1])
#x = tf.transpose(x, [0, 2, 3, 1])

In [14]:
x_out = sess.run(x)
y_out = sess.run(y)

In [15]:
x.shape

TensorShape([Dimension(15), Dimension(1), Dimension(5), Dimension(5)])

In [16]:
x_out[0, 0, :, :]

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.21668193, 0.        , 0.610115  , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.200176  , 0.        , 0.1216267 , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ]],
      dtype=float32)

In [17]:
sess.run(a[0, :, :, 0])

array([[0.21668193, 0.610115  ],
       [0.200176  , 0.1216267 ]], dtype=float32)

In [18]:
y_out[0, 0, :, :]

array([[0.21668193, 0.21668193, 0.610115  , 0.610115  ],
       [0.21668193, 0.21668193, 0.610115  , 0.610115  ],
       [0.200176  , 0.200176  , 0.1216267 , 0.1216267 ],
       [0.200176  , 0.200176  , 0.1216267 , 0.1216267 ]], dtype=float32)

In [19]:
z = tf.transpose(x, [0, 2, 3, 1])
sess.run(z).shape

(15, 5, 5, 1)

In [20]:
sess.run(w)

array([[[[1.]],

        [[1.]]],


       [[[1.]],

        [[1.]]]], dtype=float32)

In [21]:
help(tf.nn.conv2d)

Help on function conv2d in module tensorflow.python.ops.nn_ops:

conv2d(input, filter=None, strides=None, padding=None, use_cudnn_on_gpu=True, data_format='NHWC', dilations=[1, 1, 1, 1], name=None, filters=None)
    Computes a 2-D convolution given 4-D `input` and `filter` tensors.
    
    Given an input tensor of shape `[batch, in_height, in_width, in_channels]`
    and a filter / kernel tensor of shape
    `[filter_height, filter_width, in_channels, out_channels]`, this op
    performs the following:
    
    1. Flattens the filter to a 2-D matrix with shape
       `[filter_height * filter_width * in_channels, output_channels]`.
    2. Extracts image patches from the input tensor to form a *virtual*
       tensor of shape `[batch, out_height, out_width,
       filter_height * filter_width * in_channels]`.
    3. For each patch, right-multiplies the filter matrix and the image patch
       vector.
    
    In detail, with the default NHWC format,
    
        output[b, i, j, k] =
   